# Generated by Django 3.2 on 2022-03-29 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('county', models.CharField(choices=[('Antrim', 'Antrim'), ('Armagh', 'Armagh'), ('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Derry', 'Derry'), ('Donegal', 'Donegal'), ('Down', 'Down'), ('Dublin', 'Dublin'), ('Fermanagh', 'Fermanagh'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Tyrone', 'Tyrone'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], max_length=240)),
                ('address', models.TextField()),
                ('eircode', models.CharField(max_length=240)),
                ('reason_for_dog', models.TextField()),
                ('dog_hours_alone', models.IntegerField()),
                ('indoor_outdoor', models.CharField(choices=[("Don't Mind", "Don't Mind"), ('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=240)),
                ('size_of_dog', models.CharField(choices=[("Don't Mind", "Don't Mind"), ('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=240)),
                ('specific_dog', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=240)),
                ('name_breed', models.CharField(blank=True, max_length=240, null=True)),
                ('age_of_dog', models.CharField(choices=[("Don't Mind", "Don't Mind"), ('< 12 months', '< 12 months'), ('1 - 4 Years', '1 - 4 Years'), ('5 - 8 Years', '5 - 8 Years'), ('Senior', 'Senior')], max_length=240)),
                ('people_living_address', models.SmallIntegerField()),
                ('people_age', models.CharField(choices=[('18-40', '18-40'), ('41-60', '41-60'), ('61+', '61+')], max_length=240)),
                ('allergies', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=240)),
                ('children_at_address', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=240)),
                ('childrens_ages', models.CharField(blank=True, max_length=240, null=True)),
                ('accomodation_type', models.CharField(choices=[('House', 'House'), ('Townhouse', 'Townhouse'), ('Apartment', 'Apartment'), ('Other', 'Other')], max_length=240)),
                ('homeowner', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=240)),
                ('garden_type', models.TextField()),
                ('other_dogs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=240)),
                ('neutered', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=240, null=True)),
                ('other_animals', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
