# Generated by Django 3.2 on 2022-03-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20220330_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogadoption',
            name='user',
        ),
    ]
