# Generated by Django 3.2 on 2022-03-02 14:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='{{MEDIA_URL}}kittens-3535404_640.jpg', max_length=255, verbose_name='image'),
        ),
    ]
