# Generated by Django 3.2 on 2022-03-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220303_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='placeholder',
        ),
    ]
